version: "3.8"

services:
  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${REDIS_LOCAL_PORT}:${REDIS_DOCKER_PORT}
    volumes:
      - redisdb:/var/lib/redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_DOCKER_PORT}

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    hostname: mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - mysqldb:/var/lib/mysql
    command: ['mysqld',
              '--character-set-server=utf8mb4',
              '--collation-server=utf8mb4_unicode_ci']
  app:
    image: ${DOCKER_REPO}/lotalk:latest
    restart: on-failure
    depends_on:
      - mysqldb
      - redis
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /home/ec2-user/log:${BASE_DIR}
    stdin_open: true
    tty: true
    logging:
      driver: awslogs
      options:
        awslogs-group: lotalk-logs
        awslogs-stream: lotalk-logs

volumes:
  redisdb:
  mysqldb:
