spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQLDB_HOST}:${MYSQLDB_LOCAL_PORT}/${MYSQLDB_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQLDB_USER}
    password: ${MYSQLDB_ROOT_PASSWORD}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_LOCAL_PORT}
    password: ${REDIS_PASSWORD}

  jpa:
    open-in-view: true
    hibernate.ddl-auto: create
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect


server:
  tomcat:
    accesslog:
      enabled: true
      file-date-format: yy-MM-dd
      pattern: '%{yyyy-MM-dd HH:mm:ss}t %s %r %{User-Agent}i %{Referer}i %a %b %D'
      directory: access_log
      suffix: .log
      prefix: access_log_
    basedir: ${LOG_BASE_DIR}


logging:
  config: classpath:logback-dev.xml


jwt:
  secret:
    key: ${JWT_SECRET_KEY}
    token-expiration: ${JWT_TOKEN_EXPIRATION}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}