spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQLDB_HOST}:${MYSQLDB_LOCAL_PORT}/${MYSQLDB_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQLDB_USER}
    password: ${MYSQLDB_ROOT_PASSWORD}

  jpa:
    open-in-view: true
    hibernate.ddl-auto: create
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  data:
    redis:
      password: ${REDIS_PASSWORD}
      port: ${REDIS_LOCAL_PORT}
      host: ${REDIS_HOST}


logback:
  access:
    enabled: true
    config: classpath:logback-access.xml

logging:
  config: classpath:logback-dev.xml

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
    token-expiration: ${JWT_TOKEN_EXPIRATION}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}