name: Build Test

# Event trigger
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: Build Maven
    runs-on: ubuntu-latest
    steps:

    # Check out
    - name: Checkout
      uses: actions/checkout@v4

    # JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Caching dependencies
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    # Source Enviornment variables
    - name: Set Environment variables
      run: |
        echo "${{ secrets.ENVIRONMENT_VARS }}" >> .env
        export $(grep -v '^#' .env | xargs -d '\n')
      shell: bash
      
    # MAVEN
    - name: Build with Maven
      run: mvn -B package --file talk/pom.xml
 
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ always() }}
    steps:
      - name: Discord Notify
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
