name: CI/CD

# Event trigger
on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:

    # Check out
    - name: Checkout
      uses: actions/checkout@v3

    # JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Caching dependencies
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    # Source Enviornment variables
    - name: Set Environment variables
      run: |
        echo "${{ secrets.ENVIRONMENT_VARS }}" >> .env
        export $(grep -v '^#' .env | xargs -d '\n')
      shell: bash
    
    # Appication.yml
    #- name: Make application.yml
    #  run: |
    #   cd ./talk/src/main/resources
    #   touch ./application.yml
    #   echo "${{ secrets.APPLICATION_YML }}" > ./application.yml
    #  shell: bash
      
    # MAVEN
    - name: Build with Maven
      run: mvn -B package --file talk/pom.xml

    # Docker
    - name: Docker build & push to hub
      run: |
          cd ./talk
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_PASSWORD}}
          docker build -t ${{ secrets.DOCKER_REPO }}/lotalk .
          docker push ${{ secrets.DOCKER_REPO }}/lotalk

    # Deploy
    - name: Deploy to ec2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: 22
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
            sudo docker container prune -f
            sudo docker pull ${{ secrets.DOCKER_REPO }}/lotalk
            sudo rm .env
            echo "${{ secrets.ENVIRONMENT_VARS }}" >> .env
            export $(grep -v '^#' .env | xargs -d '\n')
            curl -L -O https://raw.githubusercontent.com/WonHyong/talk_backend/main/docker-compose.yml
            docker-compose up -d
            docker image prune -f
